//
//  UIColor+IMAAdditions.swift
//
//  Generated by Zeplin on 6/15/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var imaGreyishBrown: UIColor { 
		return UIColor(white: 61.0 / 255.0, alpha: 1.0)
	}

	class var imaWarmGrey: UIColor { 
		return UIColor(white: 122.0 / 255.0, alpha: 1.0)
	}

	class var imaSteelGrey: UIColor {
		return UIColor(red: 129.0 / 255.0, green: 146.0 / 255.0, blue: 142.0 / 255.0, alpha: 1.0)
	}

	class var imaBrownishGrey: UIColor { 
		return UIColor(white: 96.0 / 255.0, alpha: 1.0)
	}

	class var imaSilver: UIColor {
		return UIColor(red: 200.0 / 255.0, green: 205.0 / 255.0, blue: 205.0 / 255.0, alpha: 1.0)
	}

	class var imaSilverTwo: UIColor {
		return UIColor(red: 200.0 / 255.0, green: 205.0 / 255.0, blue: 205.0 / 255.0, alpha: 1.0)
	}

	class var imaWarmGreyTwo: UIColor { 
		return UIColor(white: 139.0 / 255.0, alpha: 1.0)
	}

	class var imaWhite: UIColor { 
		return UIColor(white: 245.0 / 255.0, alpha: 1.0)
	}

	class var imaDarkSlateBlue: UIColor {
		return UIColor(red: 19.0 / 255.0, green: 59.0 / 255.0, blue: 80.0 / 255.0, alpha: 1.0)
	}

	class var imaWhiteThree: UIColor { 
		return UIColor(white: 223.0 / 255.0, alpha: 1.0)
	}

	class var imaGrapefruit: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 83.0 / 255.0, blue: 83.0 / 255.0, alpha: 1.0)
	}

	class var imaWhiteTwo: UIColor { 
		return UIColor(white: 248.0 / 255.0, alpha: 1.0)
	}

	class var imaBlack10: UIColor { 
		return UIColor(white: 0.0, alpha: 0.1)
	}
}
